# Generated by Django 2.1.2 on 2019-01-15 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCode_Master',
            fields=[
                ('major_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='그룹코드id')),
                ('minor_id', models.IntegerField(verbose_name='세부코드id')),
                ('totamt', models.IntegerField(verbose_name='코드레이블')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INDEX_Coin', models.IntegerField(verbose_name='INDEX')),
                ('amt', models.BigIntegerField(verbose_name='금액')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(verbose_name='음원ID')),
                ('album_id', models.IntegerField(verbose_name='앨범ID')),
                ('music_title', models.CharField(max_length=30, verbose_name='음악제목')),
                ('music_genre', models.IntegerField(verbose_name='음악장르')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='발매일')),
                ('music_w', models.CharField(max_length=30, verbose_name='작사가')),
                ('music_m', models.CharField(blank=True, max_length=30, verbose_name='작곡가')),
                ('music_r', models.CharField(blank=True, max_length=30, verbose_name='편곡가')),
                ('agency', models.CharField(max_length=30, verbose_name='기획사')),
                ('music_len', models.IntegerField(blank=True, verbose_name='음원총길이')),
                ('sound_type', models.CharField(blank=True, max_length=10, verbose_name='음질종류')),
                ('lyrics', models.CharField(blank=True, max_length=254, verbose_name='가사')),
                ('music_img', models.CharField(blank=True, max_length=30, verbose_name='음원 이미지 경로')),
                ('play_cnt', models.IntegerField(blank=True, verbose_name='총 재생수')),
                ('music_price', models.IntegerField(blank=True, verbose_name='음원가격')),
                ('total_income', models.IntegerField(blank=True, verbose_name='총 음원수입')),
                ('album_ph', models.CharField(blank=True, max_length=30, verbose_name='앨범사진')),
                ('hash', models.CharField(blank=True, max_length=100, verbose_name='음원 IPFS해쉬값')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_SourceRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totcnt', models.IntegerField(verbose_name='누적횟수')),
                ('totamt', models.IntegerField(verbose_name='누적금액')),
                ('lastdate', models.DateTimeField(auto_now_add=True, verbose_name='지분 생성날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_Stake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INDEX_MS', models.IntegerField(verbose_name='Index')),
                ('ownmail', models.CharField(max_length=254, verbose_name='보유자 이메일')),
                ('per', models.IntegerField(verbose_name='지분수')),
                ('per_date', models.DateTimeField(auto_now_add=True, verbose_name='지분 생성날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_StakePer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INDEX_MSP', models.IntegerField(verbose_name='Index')),
                ('per', models.IntegerField(verbose_name='보유 지분수')),
                ('income_per', models.IntegerField(verbose_name='수익')),
                ('perdate', models.DateTimeField(auto_now_add=True, verbose_name='지분 보유날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
                ('ownmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Stake')),
            ],
        ),
        migrations.CreateModel(
            name='TUser_Atist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField(verbose_name='아티스트 id')),
                ('user_password', models.CharField(max_length=40, verbose_name='패스워드')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('music_type', models.IntegerField(blank=True, verbose_name='장르코드')),
                ('gender', models.IntegerField(verbose_name='성별')),
                ('faceph', models.CharField(blank=True, max_length=50, verbose_name='얼굴 사진')),
                ('area', models.CharField(blank=True, max_length=20, verbose_name='출생 지역')),
                ('etc', models.CharField(blank=True, max_length=254, verbose_name='특징')),
                ('authority_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TCode_Master')),
            ],
        ),
        migrations.CreateModel(
            name='TUser_Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pw', models.CharField(max_length=40, verbose_name='패스워드')),
                ('nname', models.CharField(max_length=30, verbose_name='닉네임')),
                ('profile', models.CharField(max_length=100, verbose_name='프로필이미지')),
                ('coin', models.IntegerField(verbose_name='총보유코인')),
                ('nation', models.IntegerField(verbose_name='국적코드')),
                ('pw2', models.CharField(max_length=40, verbose_name='패스워드2')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='수정일')),
                ('entdate', models.DateTimeField(auto_now_add=True, verbose_name='가입일자')),
                ('user_type', models.IntegerField(verbose_name='회원구분')),
                ('authority_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TCode_Master')),
            ],
        ),
        migrations.CreateModel(
            name='TUser_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='회사 id')),
                ('company', models.IntegerField()),
                ('company_name', models.IntegerField()),
                ('compnay_representation', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Atist')),
            ],
        ),
        migrations.AddField(
            model_name='tuser_atist',
            name='company_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Company'),
        ),
        migrations.AddField(
            model_name='tuser_atist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Basic'),
        ),
        migrations.AddField(
            model_name='tmusic_source',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Atist'),
        ),
        migrations.AddField(
            model_name='tmusic_coin',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Atist'),
        ),
        migrations.AddField(
            model_name='tmusic_coin',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source'),
        ),
    ]
