# Generated by Django 2.1.4 on 2019-01-22 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMusic_Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_coin', models.IntegerField(verbose_name='INDEX')),
                ('amt', models.BigIntegerField(verbose_name='금액')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(verbose_name='음원ID')),
                ('album_id', models.IntegerField(verbose_name='앨범ID')),
                ('music_title', models.CharField(max_length=30, verbose_name='음악제목')),
                ('music_genre', models.IntegerField(verbose_name='음악장르')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='발매일')),
                ('music_w', models.CharField(max_length=30, verbose_name='작사가')),
                ('music_m', models.CharField(blank=True, max_length=30, null=True, verbose_name='작곡가')),
                ('music_r', models.CharField(blank=True, max_length=30, null=True, verbose_name='편곡가')),
                ('agency', models.CharField(max_length=30, verbose_name='기획사')),
                ('music_len', models.IntegerField(blank=True, null=True, verbose_name='음원총길이')),
                ('sound_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='음질종류')),
                ('lyrics', models.CharField(blank=True, max_length=254, null=True, verbose_name='가사')),
                ('music_img', models.URLField(blank=True, null=True, verbose_name='음원 이미지 경로')),
                ('play_cnt', models.IntegerField(blank=True, null=True, verbose_name='총 재생수')),
                ('music_price', models.IntegerField(blank=True, null=True, verbose_name='음원가격')),
                ('total_income', models.IntegerField(blank=True, null=True, verbose_name='총 음원수입')),
                ('album_ph', models.ImageField(blank=True, max_length=30, null=True, upload_to=None, verbose_name='앨범사진')),
                ('hash', models.URLField(blank=True, null=True, verbose_name='음원 IPFS해쉬값')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_SourceRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totcnt', models.IntegerField(verbose_name='누적횟수')),
                ('totamt', models.IntegerField(verbose_name='누적금액')),
                ('lastdate', models.DateTimeField(auto_now_add=True, verbose_name='지분 생성날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_Stake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_ms', models.IntegerField(verbose_name='Index')),
                ('ownmail', models.EmailField(max_length=254, verbose_name='보유자 이메일')),
                ('per', models.IntegerField(verbose_name='지분수')),
                ('per_date', models.DateTimeField(auto_now_add=True, verbose_name='지분 생성날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
            ],
        ),
        migrations.CreateModel(
            name='TMusic_StakePer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_msp', models.IntegerField(verbose_name='Index')),
                ('per', models.IntegerField(verbose_name='보유 지분수')),
                ('income_per', models.IntegerField(verbose_name='수익')),
                ('perdate', models.DateTimeField(auto_now_add=True, verbose_name='지분 보유날짜')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source')),
                ('ownmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Stake')),
            ],
        ),
        migrations.AddField(
            model_name='tmusic_coin',
            name='music_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.TMusic_Source'),
        ),
    ]
