# Generated by Django 2.1.2 on 2019-01-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmusic_source',
            name='music_genre',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='music_m',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='music_r',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='total_income',
        ),
    ]
