# Generated by Django 2.1.2 on 2019-01-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='streaming',
            new_name='album',
        ),
    ]
