# Generated by Django 2.1.4 on 2019-02-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='music_w',
            field=models.CharField(max_length=30, null=True, verbose_name='작사가'),
        ),
    ]
