# Generated by Django 2.1.2 on 2019-01-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmusic_source',
            old_name='play_cnt',
            new_name='playcount',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='music_len',
        ),
        migrations.RemoveField(
            model_name='tmusic_source',
            name='sound_type',
        ),
    ]
