# Generated by Django 2.1.2 on 2019-01-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcode_master',
            old_name='totamt',
            new_name='code_label',
        ),
    ]
