# Generated by Django 2.1.2 on 2019-02-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documnent',
            name='document',
        ),
        migrations.AddField(
            model_name='documnent',
            name='docfile',
            field=models.FileField(null=True, upload_to='documents/%Y'),
        ),
        migrations.AlterField(
            model_name='documnent',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documnent',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
