# Generated by Django 2.1.4 on 2019-02-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertupload',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
