# Generated by Django 2.1.2 on 2019-01-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20190115_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcode_master',
            name='code_label',
            field=models.IntegerField(blank=True, verbose_name='코드레이블'),
        ),
        migrations.AlterField(
            model_name='tcode_master',
            name='minor_id',
            field=models.IntegerField(blank=True, verbose_name='세부코드id'),
        ),
    ]
