# Generated by Django 2.1.4 on 2019-02-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_streaming_music_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsertUpload',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('artist', models.IntegerField(verbose_name='아티스트')),
                ('music_m', models.IntegerField(verbose_name='작곡가')),
                ('price', models.BigIntegerField(verbose_name='가격')),
            ],
        ),
    ]
