# Generated by Django 2.1.2 on 2019-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20190121_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmusic_source',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, verbose_name='썸네일 이미지'),
        ),
    ]
