# Generated by Django 2.1.2 on 2019-01-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20190115_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser_basic',
            name='profile',
            field=models.URLField(max_length=100, verbose_name='프로필이미지'),
        ),
    ]
