# Generated by Django 2.1.2 on 2019-01-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20190123_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='음원ID'),
        ),
    ]
