# Generated by Django 2.1.4 on 2019-02-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='insertupload',
            name='document',
            field=models.FileField(null=True, upload_to='documents/%Y'),
        ),
        migrations.AddField(
            model_name='insertupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='insertupload',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='설명'),
        ),
    ]
