# Generated by Django 2.1.2 on 2019-01-15 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20190115_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcode_master',
            name='code_label',
            field=models.IntegerField(blank=True, null=True, verbose_name='코드레이블'),
        ),
        migrations.AlterField(
            model_name='tcode_master',
            name='minor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='세부코드id'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='album_ph',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='앨범사진'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='음원 IPFS해쉬값'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='lyrics',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='가사'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_img',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='음원 이미지 경로'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_len',
            field=models.IntegerField(blank=True, null=True, verbose_name='음원총길이'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_m',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='작곡가'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='음원가격'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='music_r',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='편곡가'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='play_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 재생수'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='sound_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='음질종류'),
        ),
        migrations.AlterField(
            model_name='tmusic_source',
            name='total_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 음원수입'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='출생 지역'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.TUser_Company'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='etc',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='특징'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='faceph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='얼굴 사진'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='music_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='장르코드'),
        ),
    ]
