# Generated by Django 2.1.2 on 2019-01-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_auto_20190115_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcode_master',
            name='explain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='코드 설명'),
        ),
    ]
