# Generated by Django 2.1.4 on 2019-02-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_auto_20190221_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insertupload',
            old_name='document',
            new_name='music_file',
        ),
    ]
