# Generated by Django 2.1.2 on 2019-01-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_tcode_master_explain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser_basic',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='tuser_basic',
            name='coin',
            field=models.IntegerField(blank=True, null=True, verbose_name='총보유코인'),
        ),
        migrations.AlterField(
            model_name='tuser_basic',
            name='nation',
            field=models.IntegerField(blank=True, null=True, verbose_name='국적코드'),
        ),
        migrations.AlterField(
            model_name='tuser_basic',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/%Y/%M/%D', verbose_name='프로필이미지'),
        ),
    ]
