# Generated by Django 2.1.2 on 2019-01-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_auto_20190115_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmusic_source',
            name='album_ph',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='music/%Y/%M', verbose_name='앨범사진'),
        ),
        migrations.AlterField(
            model_name='tmusic_stake',
            name='ownmail',
            field=models.EmailField(max_length=254, verbose_name='보유자 이메일'),
        ),
    ]
