# Generated by Django 2.1.4 on 2019-02-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_auto_20190221_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=75, verbose_name='해쉬')),
            ],
        ),
    ]
