# Generated by Django 2.1.2 on 2019-01-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20190115_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcode_master',
            name='explain',
        ),
        migrations.AlterField(
            model_name='tcode_master',
            name='code_label',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='코드레이블'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='faceph',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='아티스트 사진'),
        ),
    ]
