# Generated by Django 2.1.2 on 2019-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_auto_20190115_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser_atist',
            name='authority_code',
        ),
        migrations.RemoveField(
            model_name='tuser_basic',
            name='authority_code',
        ),
        migrations.AlterField(
            model_name='tcode_master',
            name='minor_id',
            field=models.IntegerField(verbose_name='세부코드id'),
        ),
    ]
