# Generated by Django 2.1.4 on 2019-02-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_insertupload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertupload',
            name='hash',
            field=models.CharField(max_length=128, null=True, verbose_name='hash'),
        ),
    ]
