# Generated by Django 2.1.2 on 2019-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_auto_20190115_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcode_master',
            name='major_id',
            field=models.IntegerField(verbose_name='그룹코드id'),
        ),
        migrations.AlterField(
            model_name='tcode_master',
            name='minor_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='세부코드id'),
        ),
    ]
