# Generated by Django 2.1.2 on 2019-01-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_auto_20190115_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser_atist',
            name='faceph',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='artist/%Y/%M/%D', verbose_name='아티스트 사진'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='gender',
            field=models.CharField(max_length=4, verbose_name='성별'),
        ),
    ]
