# Generated by Django 2.1.2 on 2019-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_auto_20190115_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmusic_source',
            name='album_ph',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to='music/%Y', verbose_name='앨범사진'),
        ),
        migrations.AlterField(
            model_name='tuser_atist',
            name='faceph',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='artist/%Y', verbose_name='아티스트 사진'),
        ),
        migrations.AlterField(
            model_name='tuser_basic',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/%Y', verbose_name='프로필이미지'),
        ),
    ]
