# Generated by Django 2.1.2 on 2019-01-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_auto_20190115_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmusic_coin',
            old_name='INDEX_Coin',
            new_name='index_coin',
        ),
        migrations.RenameField(
            model_name='tmusic_stake',
            old_name='INDEX_MS',
            new_name='index_ms',
        ),
        migrations.RenameField(
            model_name='tmusic_stakeper',
            old_name='INDEX_MSP',
            new_name='index_msp',
        ),
    ]
