# Generated by Django 2.1.4 on 2019-02-18 08:21

from django.db import migrations, models
import django.db.models.deletion
import photo.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Several Line Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Upload Date')),
                ('agency', models.CharField(max_length=30, null=True, verbose_name='기획사')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('image', photo.fields.ThumbnailImageField(upload_to='photo/%Y/%M')),
                ('image_test2', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='photo Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('agency', models.CharField(max_length=30, null=True, verbose_name='기획사')),
                ('videourl', models.URLField(max_length=50, null=True, verbose_name='유튜브')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Album')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
