# Generated by Django 2.1.2 on 2019-01-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='imate_test2',
            new_name='image_test2',
        ),
    ]
