# Generated by Django 2.1.2 on 2019-01-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_test',
            field=models.ImageField(blank=True, null=True, upload_to='null'),
        ),
        migrations.AddField(
            model_name='photo',
            name='imate_test2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
