# Generated by Django 2.1.2 on 2019-01-29 06:31

from django.db import migrations, models
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190126_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='agency',
            field=models.CharField(max_length=30, null=True, verbose_name='기획사'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(upload_to='photo/%Y/%M'),
        ),
    ]
