# Generated by Django 2.1.2 on 2019-01-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20190129_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='agency',
            field=models.CharField(max_length=30, null=True, verbose_name='기획사'),
        ),
    ]
