# Generated by Django 2.1.4 on 2019-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_opendate',
            field=models.DateField(null=True, verbose_name='데뷔일'),
        ),
    ]
