# Generated by Django 2.1.4 on 2019-01-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190116_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_company',
            field=models.CharField(blank=True, default='none', max_length=32, null=True, verbose_name='소속 기업 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, default='none', max_length=32, null=True, unique=True, verbose_name='기업 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='none', max_length=45, null=True, verbose_name='기업명'),
        ),
    ]
