# Generated by Django 2.1.4 on 2019-01-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190117_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='기업 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='기업명'),
        ),
    ]
