# Generated by Django 2.1.4 on 2019-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190117_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_id',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='아티스트 ID'),
        ),
    ]
