# Generated by Django 2.1.4 on 2019-01-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190117_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nname',
            field=models.CharField(max_length=45, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
